/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author daniela
 */
/**
 * La clase AggUsuario representa una interfaz gráfica para agregar usuarios con diferentes prioridades
 * y actualizar una lista de usuarios junto con sus documentos asociados.
 */
public class AggUsuario extends javax.swing.JFrame {

    private Lista<Usuario> listaUsuarios;
    private JTextArea textA;
    private Lista<Documento> ldoc;
    

    /**
     * Creates new form AggUsuario
     */
    /**
     * Constructor de la clase AggUsuario.
     *
     * @param listaUsuario Lista enlazada de Usuarios
     * @param texta JTextArea para mostrar información de usuarios y documentos
     * @param ldoc Lista enlazada de Documentos
     */
    public AggUsuario(Lista<Usuario> listaUsuario, JTextArea texta, Lista<Documento> ldoc) {
        initComponents();
        this.listaUsuarios = listaUsuario;
        this.textA = texta;
        this.ldoc = ldoc;

        this.setResizable(false);
        this.setTitle("AGREGAR USUARIOS");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreusuario = new javax.swing.JTextField();
        Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pAlta = new javax.swing.JButton();
        pMedia = new javax.swing.JButton();
        pBaja = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Ingrese el nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        nombreusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 38, 119, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Seleccione la prioridad asociada a su usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 347, -1));

        pAlta.setText("Alta");
        pAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAltaActionPerformed(evt);
            }
        });
        getContentPane().add(pAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        pMedia.setText("Media");
        pMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMediaActionPerformed(evt);
            }
        });
        getContentPane().add(pMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        pBaja.setText("Baja");
        pBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBajaActionPerformed(evt);
            }
        });
        getContentPane().add(pBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/pkg2/Imagenes/Pasted Graphic 2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 110));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/pkg2/Imagenes/fondoazul.jpeg"))); // NOI18N
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /**
     * Acción realizada al ingresar el nombre del usuario.
     *
     * @param evt Evento de acción (ingresar texto)
     */
    private void nombreusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreusuarioActionPerformed

    /**
     * Acción para agregar un usuario con prioridad alta.
     *
     * @param evt Evento de acción (clic en el botón de prioridad alta)
     */
    private void pAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAltaActionPerformed
        // TODO add your handling code here:
        if (!nombreusuario.getText().isEmpty()) {
            Usuario usuario = new Usuario(nombreusuario.getText(), "prioridad_alta");

            listaUsuarios.InsertarFinal(usuario);
            textA.setText(listaUsuarios.TextAreaUD(ldoc));
            JOptionPane.showMessageDialog(this, "Usuario agregado con éxito!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Error! Agregue el nombre de su usuario!");
        }

    }//GEN-LAST:event_pAltaActionPerformed
     /**
     * Acción para volver atrás.
     *
     * @param evt Evento de acción (clic en el botón de Volver)
     */
    
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed
    /**
     * Acción para agregar un usuario con prioridad media.
     *
     * @param evt Evento de acción (clic en el botón de prioridad media)
     */
    private void pMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMediaActionPerformed
        // TODO add your handling code here:
        if (!nombreusuario.getText().isEmpty()) {
            Usuario usuario = new Usuario(nombreusuario.getText(), "prioridad_media");

            listaUsuarios.InsertarFinal(usuario);
            textA.setText(listaUsuarios.TextAreaUD(ldoc));
            JOptionPane.showMessageDialog(this, "Usuario agregado con éxito!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Error! Agregue el nombre de su usuario!");
        }
    }//GEN-LAST:event_pMediaActionPerformed

    
    /**
     * Acción para agregar un usuario con prioridad baja.
     *
     * @param evt Evento de acción (clic en el botón de prioridad baja)
     */
    private void pBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBajaActionPerformed
        // TODO add your handling code here:
        if (!nombreusuario.getText().isEmpty()) {
            Usuario usuario = new Usuario(nombreusuario.getText(), "prioridad_baja");

            listaUsuarios.InsertarFinal(usuario);
            textA.setText(listaUsuarios.TextAreaUD(ldoc));
            JOptionPane.showMessageDialog(this, "Usuario agregado con éxito!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Error! Agregue el nombre de su usuario!");
        }
        
    }//GEN-LAST:event_pBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AggUsuario().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreusuario;
    private javax.swing.JButton pAlta;
    private javax.swing.JButton pBaja;
    private javax.swing.JButton pMedia;
    // End of variables declaration//GEN-END:variables
}
