/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author daniela
 */
/**
 * Esta clase representa una interfaz gráfica para eliminar usuarios.
 * Permite eliminar usuarios y sus documentos asociados.
 */
public class EliminarUsuario extends javax.swing.JFrame {

    private Lista<Usuario> listaUsuarios;
    private JTextArea textA;
    private Lista<Documento> ldoc;
    private MonticuloB mb;

    /**
     * Creates new form EliminarUsuario
     */
    /**
     * Constructor de la clase EliminarUsuario.
     *
     * @param listaUsuario Lista de usuarios
     * @param texta        Área de texto donde se muestra la información
     * @param ldoc         Lista de documentos asociados a los usuarios
     * @param mb           Montículo binario para la cola de impresión
     */
    public EliminarUsuario(Lista<Usuario> listaUsuario, JTextArea texta, Lista<Documento> ldoc, MonticuloB mb) {
        initComponents();
        this.listaUsuarios = listaUsuario;
        this.textA = texta;
        this.ldoc = ldoc;
        this.mb = mb;

        this.setResizable(false);
        this.setTitle("ELIMINAR USUARIOS");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Ingrese el usuario: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 113, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/pkg2/Imagenes/4302010.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/pkg2/Imagenes/fondoazul.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed
     /**
     * Método invocado al pulsar el botón "Volver", oculta la ventana actual.
     *
     * @param evt Evento de acción que desencadena el método
     */
    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed
    /**
     * Método invocado al pulsar el botón "Aceptar".
     * Elimina un usuario y sus documentos asociados si existen en las listas.
     *
     * @param evt Evento de acción que desencadena el método
     */
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        String nombre = usuario.getText().trim();
              

        if (listaUsuarios.buscarUsuario(nombre)) {

            for (int i = 0; i < mb.getMonticulo().length; i++) {
                Documento doc2 = (Documento) mb.getMonticulo()[i];

                if (doc2 != null) {
                    Usuario usAux = (Usuario) ldoc.getHs().getKey(usuario.getText());

                    if (usAux != null) {
                        Lista<Documento> ldocAux = (Lista<Documento>) ldoc.getHs().get(usAux);
                        Nodo pAux = ldocAux.getpFirst();

                        while (pAux != null) {
                            Documento doc = (Documento) pAux.getDato();

                            if (!doc.getNombre().equalsIgnoreCase(doc2.getNombre())) {
                                ldoc.eliminarDocUs(nombre); 
                            } else {
                                JOptionPane.showMessageDialog(this, "Eliminado con éxito, menos el documento en cola de impresión!");
                            }

                            pAux = pAux.getpNext();
                        }
                    }
                }
            }

                listaUsuarios.eliminarUsuario(nombre);
                ldoc.getHs().remove(nombre);
                

                textA.setText(listaUsuarios.TextAreaUD(ldoc));
                JOptionPane.showMessageDialog(this, "Eliminado con exito");

            
        }else {
            JOptionPane.showMessageDialog(this, "El usuario no existe");
        }
    }//GEN-LAST:event_aceptarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField usuario;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
